# Generated by Django 5.1.4 on 2024-12-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('dueDate', models.DateField(null=True)),
                ('status', models.CharField(choices=[('A', 'Open'), ('I', 'Working'), ('P', 'Pending Work'), ('C', 'Completed'), ('O', 'Overdue'), ('X', 'Cancelled')], default='P', max_length=1)),
            ],
        ),
    ]
