name: Django CI/CD Pipeline

# Trigger the workflow on any push to the main branch
on:
  push:
    branches:
      - main

jobs:
  test-and-lint:
    # Run the pipeline on an Ubuntu environment
    runs-on: ubuntu-latest

    # Define pipeline steps
    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up Python 3.11
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run Django tests
    - name: Run tests
      run: python manage.py test

    # Step 5: Check code formatting with Black
    - name: Lint code with Black
      run: black --check .

    # Step 6: Check code style with Flake8
    - name: Lint code with Flake8
      run: flake8 .
